### ISSUE TITLE
Which client and server?

### ISSUE THREAD

**Issue by FrancisPouliot** [opentimestamps/opentimestamps.org#25]
I'm curious as to which version of the client the website is using and how the calendars are selected (for research purposes)

**Comment by RCasatta** [comment]
The web site use the javascript library of course, I am not completely sure which version the last time we bundle it with the web site, @lvaccaro could help. Definitely helpful to put a disclaimer about which version is used for debugging reasons.
The calendars used are: 
* https://alice.btc.calendar.opentimestamps.org/
* https://bob.btc.calendar.opentimestamps.org/
* https://finney.calendar.eternitywall.com/

which are the same bundled with the python reference implementation.
There aren't yet formal rules on the selection process but I could say they are selected based on the commitment on the project of the maintainer and his previous work on the protocol. It's ideal the number of calendars it's enough to not depend on just a few entities but not too big because otherwise there are too many superfluous tx on chain. Maybe @petertodd could integrate on this or correct me if I am wrong.

**Comment by FrancisPouliot** [comment]
Thanks! What do you think about OTS clients having in the GUI the option to manually select a server? Could that cause any problems?

**Comment by RCasatta** [comment]
Any custom client is obviously free to choose the preferred policy. I would always recommend to choose more than one server to maximize reliability. Thus I probably suggest a GUI which let users to to optionally deselect a calendar from a set of selected by default calendars

**Comment by petertodd** [comment]
@FrancisPouliot An important thing to remember with the OTS ecosystem is that using non-standard calendars creates timestamps that other users will have a hard time verifying due to the calendar whitelist. It's ok if a timestamp has non-standard calendars *in addition to* the standard ones, but a timestamp exclusively composed of non-standard calendars can't be verified by default.

So while manually *adding* an additional calendar is ok, *changing* the set of calendars is a very advanced feature that users will almost always not want.

**Comment by lvaccaro** [comment]
@FrancisPouliot, opentimestamps js lib used in the opentimestamps.org website is aligned with the updates of [javascript-opentimestamps](https://github.com/opentimestamps/javascript-opentimestamps). In the [opentimestamps.min.js](https://opentimestamps.org/assets/javascripts/vendor/opentimestamps.min.js), the 1st line contains the repository name and version number.
