### ISSUE TITLE
Error message for bad timestamp doesn't make sense

### ISSUE THREAD

**Issue by petertodd** [opentimestamps/opentimestamps.org#28]
Specifically attempting to verify https://github.com/opentimestamps/opentimestamps-client/blob/master/examples/bad-stamp.txt / https://github.com/opentimestamps/opentimestamps-client/blob/master/examples/bad-stamp.txt.ots

![bad-stamp-output](https://user-images.githubusercontent.com/7042/37251789-c4d39126-24ec-11e8-90ca-573748a39bdc.png)

The error message from the client would be better:

```
$ ots verify bad-stamp.txt.ots 
Assuming target filename is 'bad-stamp.txt'
Bitcoin verification failed: Digest does not match merkleroot
```

**Comment by petertodd** [comment]
Also, the error message in this example is also bad: https://github.com/opentimestamps/opentimestamps-client/blob/master/examples/unknown-notary.txt / https://github.com/opentimestamps/opentimestamps-client/blob/master/examples/unknown-notary.txt.ots

**Comment by lvaccaro** [comment]
Fixed with library update
* bad-stamp: Failure message
<img width="453" alt="screen shot 2018-03-27 at 12 45 55" src="https://user-images.githubusercontent.com/11627784/37962902-f6d2ea32-31bc-11e8-9907-55147f78ec95.png">

* unknown-notary : Pending message, because timestamp is not completed <- is it right? 
<img width="457" alt="screen shot 2018-03-27 at 12 46 18" src="https://user-images.githubusercontent.com/11627784/37962903-f89b6dd0-31bc-11e8-88cb-6f3b667901ee.png">

**Comment by lvaccaro** [comment]
Thanks for the explanation. Fix in https://github.com/opentimestamps/opentimestamps.org/commit/d922b40e3f9c0c146883d3d44fb18f723ade1443
* unknown notary: unknown attestation message
<img width="455" alt="screen shot 2018-03-30 at 16 55 05" src="https://user-images.githubusercontent.com/11627784/38142608-4d5b38c8-343d-11e8-941c-aaa00746aafc.png">

* known and unknown notary: show only the valid one
<img width="454" alt="screen shot 2018-03-30 at 16 54 59" src="https://user-images.githubusercontent.com/11627784/38142612-54960028-343d-11e8-9b0c-7dd6299d8203.png">

**Comment by petertodd** [comment]
It'd be a bit better if it said "Unknown attestation type" rather than "Unknown attestation" - makes it a little more clear what the problem actually is.
