### ISSUE TITLE
Ethereum and Opentimestamps

### ISSUE THREAD

**Issue by march76** [opentimestamps/opentimestamps.org#47]
Hi @RCasatta and @petertodd, 
will OpenTimestamps also include the use of Ethereum Smart Contract ?

**Comment by petertodd** [comment]
OpenTimestamps doesn't do anything for which a "smart contract" is required: it simply proves that data existed in the past.

OTS does have ETH support in the protocol. But currently it's not really used, and would have no advantages over BTC. An experimental ETH calendar was maintained for awhile, but due to the low reliability of ETH nodes it was discontinued.

**Comment by march76** [comment]
@petertodd Thanks for the reply.
Can you clarify the problems encountered with ETH due to the poor reliability of the ETH nodes?
ETH is a  very reliable and consolidated network: I am worried about your statement.
Can you give more details?
Thanks in advance

**Comment by petertodd** [comment]
I wasn't the one running it personally. But the guy who was kept having their node crash.

ETH simply isn't as reliable as BTC.
